news/urls.py
from django.urls import path
from .views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB, GiornalistaListView

app_name = 'news'

urlpatterns = [
    path("", home, name="homeview"),
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_"),
    path("giornalisti/<int:pk>", GiornalistaDetailViewCB.as_view(), name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_giornalisti"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_"),
]

prima_app/urls.py
  
from django.urls import path
from .views import homepage, menu, chisiamo, variabili, index
app_name = 'prima_app'
urlpatterns = [
    path('welcome/', homepage, name='home'),
    path('menu/', menu, name='menu'),
    path('chisiamo/', chisiamo, name='chisiamo'),
    path('variabili/', variabili, name='variabili'),
    path('index/', index, name='index')
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from prima_app.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("prima_app/", include("prima_app.urls")),
    path("seconda_app/", include("seconda_app.urls")),
    path("news/", include("news.urls")),
    path("libreria/", include("libreria.urls")),
    path("forms_app/", include("forms_app.urls")),
    path("", index, name="index")
]

seconda_app/urls.py
  
from django.urls import path
from .views import esif, ifelse, ifelif, esfor

app_name = "seconda_app"
urlpatterns = [
    path("if/", esif, name="if"),
    path("ifelse/", ifelse, name="ifelse"),
    path("ifelif/", ifelif, name="ifelif"),
    path("for/", esfor, name="for"),
]

prima_app/models.py
from django.db import models

# Create your models here.

prima_app/views.py
  
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def homepage(request):
    return render(request, "homepage.html")


def menu(request):
    return render(request, "menu.html")


def chisiamo(request):
    return render(request, "chi-siamo.html")


def variabili(request):
    context = {
        "var1": "Variabile numero 1",
        "var2": "Variabile numero 2",
        "var3": "Variabile numero 3",
    }
    return render(request, "variabili.html", context)


def index(request):
    return render(request, "index.html")

prima_app/templates/chi_siamo.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Chi siamo {% endblock title %}
{% block content %}
<h1>Chi siamo?</h1>
<p>Noi siamo quelli che quando decidono di fare qualcosa... Poi comunque la facciamo!</p>
{% endblock content %}

prima_app/templates/homepage.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Homepage {% endblock title %}
{% block content %} <h1>Benvenuti nella homepage!</h1> {% endblock content %}

prima_app/templates/index.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Index {% endblock title %}
{% block content %}
<h1>Index</h1>
    <ul>
        <li>Prima app</li>
        <ul>
            <li><a href="{% url 'prima_app:homepage' %}">Homepage</a></li>
            <li><a href="{% url 'prima_app:menu' %}">Menu</a></li>
            <li><a href="{% url 'prima_app:chi-siamo' %}">Chi siamo</a></li>
            <li><a href="{% url 'prima_app:variabili' %}">Variabili</a></li>
        </ul>
        <li>Seconda app</li>
        <ul>
            <li><a href="{% url 'seconda_app:if' %}">Esercizio if</a></li>
            <li><a href="{% url 'seconda_app:ifelse' %}">Esercizio if-else</a></li>
            <li><a href="{% url 'seconda_app:ifelif' %}">Esercizio if-elif</a></li>
            <li><a href="{% url 'seconda_app:for' %}">Esercizio for</a></li>
        </ul>
    </ul>
{% endblock content %}

prima_app/templates/menu.html
{% extends 'base.html' %}
{% block title %} {{block.super}} | Menu {% endblock title %}
{% block content %}
    <ol>
        <li>Voce numero 1</li>
        <li>Voce numero 2</li>
        <li>Voce numero 3</li>
    </ol>
{% endblock content %}

prima_app/templates/variabili.html
  
{% extends 'base.html' %}
{% block title %} {{block.super}} | Variabili {% endblock title %}
{% block content %}
    <ol>
        <li>{{var1}}</li>
        <li>{{var2}}</li>
        <li>{{var3}}</li>
    </ol>
{% endblock content %}