forms_app/urls.py
from django.urls import path
from .views import contatti

app_name = "forms_apps"

urlpatterns=[
    path('contattaci/', contatti, name='contatti'),
]

libreria/urls.py
from django.urls import path
from .views import AutoreDetail_MS, LibroList_MS

app_name = 'libreria'

urlpatterns = [
    path('', LibroList_MS.as_view(), name='lista_libri'),
    path('autore/<int:pk>/', AutoreDetail_MS.as_view(), name='profilo_autore')
]

news/urls.py
from django.urls import path
from .views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB, GiornalistaListView

app_name = 'news'

urlpatterns = [
    path("", home, name="homeview"),
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_"),
    path("giornalisti/<int:pk>", GiornalistaDetailViewCB.as_view(), name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_giornalisti"),
    path("lista_giornalisti/", GiornalistaListView.as_view(), name="lista_"),
]

prima_app/urls.py
  
from django.urls import path
from .views import homepage, menu, chisiamo, variabili, index
app_name = 'prima_app'
urlpatterns = [
    path('welcome/', homepage, name='home'),
    path('menu/', menu, name='menu'),
    path('chisiamo/', chisiamo, name='chisiamo'),
    path('variabili/', variabili, name='variabili'),
    path('index/', index, name='index')
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from prima_app.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("prima_app/", include("prima_app.urls")),
    path("seconda_app/", include("seconda_app.urls")),
    path("news/", include("news.urls")),
    path("libreria/", include("libreria.urls")),
    path("forms_app/", include("forms_app.urls")),
    path("", index, name="index")
]

seconda_app/urls.py
  
from django.urls import path
from .views import esif, ifelse, ifelif, esfor

app_name = "seconda_app"
urlpatterns = [
    path("if/", esif, name="if"),
    path("ifelse/", ifelse, name="ifelse"),
    path("ifelif/", ifelif, name="ifelif"),
    path("for/", esfor, name="for"),
]

primo_progetto/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Web apps{% endblock title %}</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">Primo Progetto</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/"> <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Prima
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'prima_app:index' %}">Index</a>
                <a class="dropdown-item" href="{% url 'prima_app:homepage' %}">Home</a>
                <a class="dropdown-item" href="{% url 'prima_app:chi-siamo' %}">Chi siamo</a>
                <a class="dropdown-item" href="{% url 'prima_app:variabili' %}">Variabili</a>

            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Seconda
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'seconda_app:if' %}">if</a>
              <a class="dropdown-item" href="{% url 'seconda_app:ifelse' %}">ifelse</a>
              <a class="dropdown-item" href="{% url 'seconda_app:ifelif' %}">ifelif</a>
              <a class="dropdown-item" href="{% url 'seconda_app:for' %}">for</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                News
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'news:lista_articoli' %}">Articoli</a>
                <a class="dropdown-item" href="{% url 'news:lista_giornalisti' %}">Giornalisti</a>

            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
                Libreria
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'libreria:lista_libri' %}">Libri</a>

            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Contatti
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'forms_app:contatti' %}">Contattaci</a>
            </div>
          </li>
        </ul>

      </div>
    </nav>

    <div class="container my-4">
      <h3></h3>
     {%block content%}

     {%endblock content%}
    </div>

   </body>
</html>